[project]
name = "virt-econ"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioredis>=2.0.1",
    "alembic>=1.17.2",
    "fastapi>=0.121.2",
    "sqlalchemy>=2.0.44",
]
